newsletter_sender_job:
  cron: "0 16 * * FRI"
  class: "NewsletterSenderWorker"

post_receiver_job:
  cron: "0 * * * *"
  class: "PostReceiverWorker"

hello_world_job:
  cron: "* * * * *"
  class: "HelloWorldWorker"
